title: Oscar's Homepage
page-top-title: Oscar Smee
top-section-bg-text: Optimisation and Machine Learning 
home-subtitle: Oscar Smee
copyright-text: '&copy; Oscar Smee 2023-2024. All Rights Reserved.'
